spring:
    datasource:
        url: jdbc:mysql://localhost:3306/tecwebike?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
        username: root
        password: 123456789
    liquibase:
        change-log: "classpath:db/changelog/db.changelog-master.xml"
    security:
        oauth2:
            resourceserver:
              jwt:
                  issuer-uri: https://dev-0hjo6w8t.us.auth0.com/
